### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by LucasVeerman** [SIELOnline/Acumulus-for-Magento1#1]
I'm getting a fatal error because the "app/code/community/Siel/Acumulus/lib/siel/acumulus" folder is missing a file.

**Comment by fietserwin** [comment]
Which file?

**Comment by LucasVeerman** [comment]
Actually the whole folder is empty.

**Comment by fietserwin** [comment]
Then you need to install it by downloading it from https://github.com/SIELOnline/libAcumulus. The library project comes as a separate install since Magento 2 started to work with composer. But why not using the install package from the Siel forum at https://forum.acumulus.nl/index.php/topic,3817.0.html that does contain the library?
